# yaml-language-server: $schema=https://raw.githubusercontent.com/octo-sts/app/refs/heads/main/pkg/octosts/octosts.OrgTrustPolicy.json
issuer: https://token.actions.githubusercontent.com
audience: octo-sts.their.net
subject: repo:connectbot@5605419/cbtelnet@1406858044:ref:refs/heads/main

claim_pattern:
  repository: "^connectbot/cbtelnet$"
  event_name: "^issues$"
  job_workflow_ref: "^connectbot/release-action/\\.github/workflows/prepare-release\\.yml@2085a1d6887933a5e65e1007dd446bb07b3b6067$"

permissions:
  contents: write
  pull_requests: write
  issues: write

repositories:
  - cbtelnet
