# yaml-language-server: $schema=https://raw.githubusercontent.com/octo-sts/app/refs/heads/main/pkg/octosts/octosts.OrgTrustedIssuers.json
mode: enforce
issuers:
  - https://token.actions.githubusercontent.com
